### ISSUE TITLE
ModuleNotFoundError: No module named 'quartapp'

### ISSUE THREAD

**Issue by greenstartech** [john0isaac/rag-semantic-kernel-mongodb-vcore#45]
Getting an error when trying to run add_data.py

**To Reproduce**
1. SSH to web application
2. Run 'python ./scripts/add_data.py'
3. Generates the following error.

root@11d666909ff7:/tmp/8dd26907ecff976# **python ./scripts/add_data.py**
Traceback (most recent call last):
  File "/tmp/8dd26907ecff976/./scripts/add_data.py", line 10, in <module>
    from quartapp.rag import initialize_sk_chat_embedding, initialize_sk_memory_store
ModuleNotFoundError: No module named 'quartapp'

**Additional context**
Python 3.12.2

**Comment by john0isaac** [comment]
Hey @greenstartech,
thank you for reporting and sorry for the delay.

Run this command `pip install -e .` before trying to execute the script in the cloud shell.


```sh
pip install -e .
python ./scripts/add_data.py
```

I'm adding it to the readme.
