### ISSUE TITLE
Fail to load web page after "azd up"

### ISSUE THREAD

**Issue by Menghua1** [john0isaac/rag-semantic-kernel-mongodb-vcore#8]
**Describe the issue:**
After running the `azd up` command and clicking on the endpoint URI in the output, the following error appears:
![image](https://github.com/john0isaac/rag-semantic-kernel-mongodb-vcore/assets/111940661/62a3b1b5-e19e-40e3-9504-c94c90f7af80)
**Repro Steps:**
1. Clone code.
2. Run `azd auth login`.
3. Run `azd up`.
4. Click the endpoint URI in the output.

**Environment:**

- Azd version: `azd version 1.8.0 (commit 8246323c2472148288be4b3cbc3c424bd046b985)`
- OS: Window 11

**Expected behavior:**
The web pag can load normally.

@john0isaac and @hemarina for notification.

**Comment by john0isaac** [comment]
Hey @Menghua1,
Thank you for testing.

Can you please confirm that the deployment succeeded from Azure App Service?

The website works perfectly fine after deploying but sometimes the deployment part fails which requires you to run `azd deploy` to deploy the website successfully.

**Comment by john0isaac** [comment]
@Menghua1 
I just deployed this and it works fine for me.
![image](https://github.com/john0isaac/rag-semantic-kernel-mongodb-vcore/assets/64026625/eb8765c7-6402-470f-9c0d-e79768b41bae)



![image](https://github.com/john0isaac/rag-semantic-kernel-mongodb-vcore/assets/64026625/871e27ce-371f-4222-8739-6c1bf18fee30)

**Comment by john0isaac** [comment]
@Menghua1 No worries, Thank you so much!
